trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: yarn  --ignore-engines
  displayName: 'Install npm modules'

- script: yarn lint
  displayName: 'Lint UI, libs and extension tests in parallel'

- script: yarn test
  displayName: 'Run UI, libs and extension tests in parallel'

- script: yarn build
  displayName: 'Compile UI, libs and extension tests in parallel'

- script: yarn e2e-test
  displayName: 'End to End Tests'

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Agent.BuildDirectory)/s/out/dist
    artifact: dist
  displayName: 'Publish output'

- task: PublishBuildArtifacts@1
  inputs:
    path: $(Agent.BuildDirectory)/s/test-resources/screenshots/*
    artifact: screenshots
  condition: succeededOrFailed()
  displayName: 'Publish e2e screenshots'