trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: yarn  --ignore-engines
  displayName: 'Install npm modules'

- script: yarn lint
  displayName: 'Lint UI, libs and extension tests in parallel'

- script: yarn test
  displayName: 'Run UI, libs and extension tests in parallel'

- script: yarn build
  displayName: 'Compile UI, libs and extension tests in parallel'

- script: yarn e2e-test
  displayName: 'End to End Tests'

- task: PublishPipelineArtifact@0
  displayName: 'Publish vsix artifact'
  inputs:
    targetPath: $(Agent.BuildDirectory)/s/out/dist
    archiveFilePatterns: '**/*.vsix'

#- task: PublishPipelineArtifact@1
#  inputs:
#    archiveFilePatterns: $(Agent.BuildDirectory)/s/out/dist/*.vsix
#    artifact: dist
#  displayName: 'Publish vsix artifact'

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Agent.BuildDirectory)/s/test-resources/screenshots
    artifact: screenshots
  condition: failed()
  displayName: 'Publish e2e results'

# TODO need to enable auto releaes of extension
#- script: yarn publish
#  displayName: 'Build exention'
